### ISSUE TITLE
Allowing Conditional Updates

### ISSUE THREAD

**Issue by courtenayparserr** [angusmillar/Pyro#3]
Hi Angus,

Firstly: thank you. What an awesome implementation. Really enjoying it so far.

Curious - do you allow conditional updates?

Specifically: https://www.hl7.org/fhir/http.html#upsert

> Servers MAY choose to allow clients to PUT a resource to a location that does not yet exist on the server - effectively, allowing the client to define the id of the resource. 

When I sent through an id, it returned a new ID for the Patient.

Reason being is we are syncing two FHIR servers and thought it may be possible to do this.

Thanks again!

**Comment by angusmillar** [comment]
You have asked about 'conditional updates' yet you have provided a link to 'update as create'. Does not matter, the server supports both. It should all work as documented in the specification. Ask more questions if you need to. Happy to look into an issue if you are having one.

**Comment by courtenayparserr** [comment]
Sorry got my terms mixed. I've pulled down your develop-r4 branch and trying to do the following:

Execute a PUT on this blob here: https://www.hl7.org/fhir/patient-example.json.html

Notice it has an Id of "example". And it won't exist in the DB at this stage. What I wanted to happen was for the item to be created with that Id instead of a new Id? Note: The Id's are not guids...

Thanks Angus!

**Comment by angusmillar** [comment]
That should work, you will need to have the resource id on the end of the PUT url, like this:

PUT: [base]/Patient/example

The exact same id 'example' must also be in the resource as its id.

**Comment by courtenayparserr** [comment]
Champion! Thank you. That worked!

**Comment by angusmillar** [comment]
Glad to hear.
